name: Publish style guide

on:
  push:
    branches:
      - master
    paths:
    - 'packages/guide/content/**/*.md'

jobs:
  publish-guide:
    name: Publish style guide
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: npm install
      working-directory: ./packages/guide
    - run: yarn build
      working-directory: ./packages/guide
    - run: rm package-lock.json
      working-directory: ./packages/guide
    - run: npm install
      working-directory: ./packages/theme-eisbaer
    - run: yarn build
      working-directory: ./packages/theme-eisbaer
    - run: rm package-lock.json
      working-directory: ./packages/theme-eisbaer
    - run: |
          git config user.name hobbes7878
          git config user.email jon.r.mcclure@gmail.com
          git add .
          git commit -m "update style guide"
          git push
